#!/usr/bin/env python3
# NetDog Client module, alpha release
# Copyright 2018, 2019 Aswin Babu Karuvally

# import serious stuff
from libgreen import *


# the main function
def main():
    # initialize the system
    initialize_system()

    # start listening for connections
    listen_thread = threading.Thread(target=create_new_listen_socket,
        args = [1994])

    listen_thread.start()

    # make sure we have usable network
    setup_network()
    
    # start beacon system
    beacon_thread = threading.Thread(target=beacon_system)
    beacon_thread.start()

# call the main function
if __name__ == "__main__":
    main()
